### ISSUE TITLE
gif2png Broken conversion of animated gifs

### ISSUE THREAD

**Issue by Yoshqu** [robert-ancell/pygif#7]
Next deltas seems to be slanted - as if notion of "non changed part" was not decoded. I'm no expert on this so sorry for my guessing.
https://www.animatedimages.org/data/media/198/animated-frog-image-0015.gif
https://www.animatedimages.org/data/media/140/animated-love-image-0187.gif

Some are lacking 'clearing out' previous data.
https://www.animatedimages.org/data/media/140/animated-love-image-0040.gif

I know that most simple thing to do, would be dump of first frame only - but still it would be nice to have demo which dumps all the frames

**Comment by robert-ancell** [comment]
Should be fixed now, thanks for filing!
